<div class="col-sm-12">
    <table class="table">
        <tbody>
            <tr>
                <td>@lang('head.name')</td>
                <td>{{$student->name}} {{$student->lastname}}</td>
            </tr>
            <tr> 
                <td>@lang('head.birthdate')</td>
                <td>{{$student->birthdate}}</td>
            </tr>
            <tr>
                <td>@lang('head.gender')</td>
                <td>{{$student->gender}}</td>
            </tr>
            <tr>
                <td>@lang('head.curp')</td>
                <td>{{$student->curp}}</td>
            </tr>
            <tr>   
                <td>@lang('head.mobile')</td>
                <td>{{$student->mobile}}</td>
            </tr>
            <tr> 
                <td>@lang('head.phone')</td>
                <td>{{$student->phone}}</td>
            </tr>
            <tr> 
                <td>@lang('head.emergency_phone')</td>
                <td>{{$student->emergency_phone}}</td>
            </tr>
            <tr> 
                <td>@lang('head.blood_type')</td> 
                <td>{{$student->blood_type}}</td>
            </tr>
            <tr>
                <td>@lang('head.allergy')</td>
                <td>{{$student->allergy}}</td>
            </tr>
            <tr>
                <td>@lang('head.email')</td>
                <td>{{$student->email}}</td>
            </tr>
            <tr>
                <td>@lang('head.address')</td>
                <td>{{$student->address}}</td>
            </tr>
            <tr> 
                <td>@lang('head.comments')</td> 
                <td>{{$student->comment}}</td>
            </tr>
            <tr>
                <td>@lang('head.registration_date')</td>
                <td>{{$student->registration_date}}</td>
            </tr>
            <tr>
                <td>@lang('head.branch')</td>
                <td>{{$student->branch->name}}</td>
            </tr>
            <tr>
                <td>@lang('head.status')</td>
                <td>{{$student->status->status}}</td>
            </tr>
        </tbody>
    </table>
</div>