<div class="col-sm-12">
    <table class="table">
        <tbody>
            <tr>
                <td>@lang('head.name')</td>
                <td>{{$professor->name}} {{$professor->lastname}}</td>
            </tr>
            <tr>
                <td>@lang('head.birthdate')</td>
                <td>{{$professor->birthdate}}</td>
            </tr>
            <tr>
                <td>@lang('head.gender')</td>
                <td>{{$professor->gender}}</td>
            </tr>
            <tr>
                <td>@lang('head.career')</td>
                <td>{{$professor->career}}</td>
            </tr>
            <tr>
                <td>@lang('head.cedula')</td>
                <td>{{$professor->cedula}}</td>
            </tr>
            <tr>
                <td>@lang('head.curp')</td>
                <td>{{$professor->curp}}</td>
            </tr>
            <tr>
                <td>@lang('head.rfc')</td>
                <td>{{$professor->rfc}}</td>
            </tr>
            <tr>
                <td>@lang('head.mobile')</td>
                <td>{{$professor->mobile}}</td>
            </tr>
            <tr>
                <td>@lang('head.phone')</td>
                <td>{{$professor->phone}}</td>
            </tr>
            <tr>
                <td>@lang('head.blood_type')</td>
                <td>{{$professor->blood_type}}</td>
            </tr>
            <tr>
                <td>@lang('head.address')</td>
                <td>{{$professor->address}}</td>
            </tr>
            <tr>
                <td>@lang('head.email')</td>
                <td>{{$professor->email}}</td>
            </tr>
            <tr>
                <td>@lang('head.hired')</td> 
                <td>{{$professor->hired}}</td>
            </tr>
        </tbody>
    </table>
</div>